apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse-local.keeperFullname" . }}-headless
  labels:
    {{- include "clickhouse-local.labels" . | nindent 4 }}
    app.kubernetes.io/component: keeper
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: keeper
  ports:
    - name: keeper
      port: {{ .Values.service.keeperPort }}
      targetPort: keeper
    - name: raft
      port: {{ .Values.service.keeperRaftPort }}
      targetPort: raft
