apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" . }}
type: Opaque

stringData:
  CLICKHOUSE_USER: {{ .Values.auth.username | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.auth.password | quote }}
