apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" . }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: {{ include "clickhouse.fullname" . }}

  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http

    - name: native
      port: {{ .Values.service.nativePort }}
      targetPort: native

    - name: interserver
      port: {{ .Values.service.interserverPort }}
      targetPort: interserver
