replicaCount: 1

image:
  registry: docker.arvancloud.ir
  repository: clickhouse/clickhouse-server
  tag: "25.5"
  pullPolicy: IfNotPresent

auth:
  username: default
  password: changeme

service:
  type: ClusterIP
  httpPort: 8123
  nativePort: 9000
  interserverPort: 9009

persistence:
  enabled: true
  size: 20Gi
  accessMode: ReadWriteOnce
  storageClassName: ""

resources:
  requests:
    cpu: 500m
    memory: 1Gi

  limits:
    cpu: 2
    memory: 4Gi

nodeSelector: {}

tolerations: []

affinity: {}
