image:
  registry: docker.arvancloud.ir
  repository: clickhouse/clickhouse-server
  tag: "26.3"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

clickhouse:
  replicas: 3
  storage:
    size: 10Gi
    storageClassName: ""
  resources: {}
  # Example:
  # resources:
  #   requests:
  #     cpu: 500m
  #     memory: 1Gi
  #   limits:
  #     cpu: "2"
  #     memory: 4Gi

keeper:
  replicas: 3
  storage:
    size: 5Gi
    storageClassName: ""
  resources: {}
  # Example:
  # resources:
  #   requests:
  #     cpu: 250m
  #     memory: 512Mi
  #   limits:
  #     cpu: "1"
  #     memory: 1Gi

service:
  httpPort: 8123
  tcpPort: 9000
  keeperPort: 9181
  keeperRaftPort: 9234
  interserverPort: 9009

podSecurityContext:
  fsGroup: 101

securityContext:
  runAsUser: 101
  runAsGroup: 101
  runAsNonRoot: true
